name: Build and Deploy (Spring Boot + Vue)

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_BACKEND_URI }} ./backend
          docker push ${{ secrets.ECR_REPO_BACKEND_URI }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_FRONTEND_URI }} ./frontend
          docker push ${{ secrets.ECR_REPO_FRONTEND_URI }}

      - name: Deploy backend to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME_BACKEND }} \
            --force-new-deployment

      - name: Deploy frontend to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME_FRONTEND }} \
            --force-new-deployment
